language: ruby
before_script:
  - RAILS_ENV=test bin/rails db:create db:schema:load
script:
  - travis/test_runner.rb
addons:
  code_climate:
    repo_token: 9a63f9f520b9847ca0ac90c94996618520325c8847986394e9b3f13bbd57b227
